# Generated by Django 5.0.1 on 2024-02-08 01:14

import django.db.models.deletion
import django.utils.timezone
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('careers', '0001_initial'),
        ('contributions', '0001_initial'),
        ('extras', '0002_leavecounter'),
        ('shift', '0002_alter_shift_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PositionPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_permissions', to='users.position')),
            ],
            options={
                'unique_together': {('position', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privilege', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('suffix', models.CharField(blank=True, choices=[('', ''), ('Jr.', 'Jr.'), ('Sr.', 'Sr.'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X'), ('Other', 'Other')], default='', max_length=10, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=255, null=True)),
                ('educational_attainment', models.CharField(choices=[('Elementary', 'Elementary'), ('High School', 'High School'), ('College Undergrad', 'College Undergrad'), ('College', 'College'), ('Masters', 'Masters'), ('Doctorate', 'Doctorate')], max_length=30)),
                ('civil_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Separated', 'Separated'), ('Widow', 'Widow'), ('Other', 'Other')], max_length=10)),
                ('mothers_maiden_name', models.CharField(max_length=50)),
                ('emergency_contact', models.CharField(max_length=50)),
                ('emergency_contact_number', models.CharField(max_length=20)),
                ('employee_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('employement_date', models.DateField(blank=True, null=True)),
                ('salary_per_day', models.FloatField(default=0.0)),
                ('number_of_days', models.IntegerField(default=0)),
                ('pag_ibig_number', models.IntegerField(null=True, unique=True)),
                ('philhealth_number', models.IntegerField(null=True, unique=True)),
                ('sss_number', models.IntegerField(null=True, unique=True)),
                ('tin_number', models.IntegerField(null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('career', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='careers.careers')),
                ('deductions', models.ManyToManyField(to='extras.deductions')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('incentives', models.ManyToManyField(to='extras.incentives')),
                ('pag_ibig_contribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contributions.pagibig')),
                ('philhealth_contribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contributions.philhealth')),
                ('shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shift.shift')),
                ('sss_contribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contributions.sss')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_users', to='users.department')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_users', to='users.position')),
                ('privilege', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.privilege')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', users.models.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_permissions', to='users.department')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'unique_together': {('department', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='PrivilegesPermission',
            fields=[
                ('positionpermission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.positionpermission')),
                ('privileges', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privilege_permissions', to='users.privilege')),
            ],
            bases=('users.positionpermission',),
        ),
    ]
