# Generated by Django 5.0.1 on 2024-02-19 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0003_number_of_leaves'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_of_leaves',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='extras.number_of_leaves'),
        ),
    ]
