# Generated by Django 5.0 on 2023-12-19 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='career',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='careers.careers'),
        ),
        migrations.AddField(
            model_name='user',
            name='civil_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Separated', 'Separated'), ('Widow', 'Widow'), ('Other', 'Other')], default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='educational_attainment',
            field=models.CharField(choices=[('Elementary', 'Elementary'), ('High School', 'High School'), ('College Undergrad', 'College Undergrad'), ('College', 'College'), ('Masters', 'Masters'), ('Doctorate', 'Doctorate')], default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='suffix',
            field=models.CharField(choices=[('Jr.', 'Jr.'), ('Sr.', 'Sr.'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X'), ('Other', 'Other')], default=None, max_length=10),
            preserve_default=False,
        ),
    ]
