# Generated by Django 5.0 on 2023-12-21 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
        migrations.AddField(
            model_name='privilege',
            name='permission',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='privileges', to='users.permission'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='privilege',
            unique_together={('privileges', 'permission')},
        ),
        migrations.DeleteModel(
            name='PrivilegesPermission',
        ),
    ]
