# Generated by Django 5.0.1 on 2024-03-07 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_number_of_leaves'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='employement_date',
            new_name='employment_date',
        ),
    ]
