# Generated by Django 5.0 on 2023-12-21 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_permission_privilege_permission_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privilege',
            old_name='privileges',
            new_name='privilege',
        ),
        migrations.AlterUniqueTogether(
            name='privilege',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='privilege',
            name='permission',
        ),
        migrations.CreateModel(
            name='PrivilegesPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('privileges', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privilege_permissions', to='users.privilege')),
            ],
            options={
                'unique_together': {('privileges', 'permission')},
            },
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
