# Generated by Django 5.0 on 2024-01-12 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_privilegespermission_position'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='privilegespermission',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='PositionPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_permissions', to='users.position')),
            ],
            options={
                'unique_together': {('position', 'permission')},
            },
        ),
        migrations.AddField(
            model_name='privilegespermission',
            name='positionpermission_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.positionpermission'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='privilegespermission',
            name='id',
        ),
        migrations.RemoveField(
            model_name='privilegespermission',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='privilegespermission',
            name='position',
        ),
        migrations.CreateModel(
            name='DepartmentPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_permissions', to='users.department')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'unique_together': {('department', 'permission')},
            },
        ),
    ]
