# Generated by Django 5.0 on 2023-12-22 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0001_initial'),
        ('users', '0003_rename_privileges_privilege_privilege_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_of_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='pag_ibig_number',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contributions.pagibigaccount'),
        ),
        migrations.AddField(
            model_name='user',
            name='philhealth_contribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contributions.philhealth'),
        ),
        migrations.AddField(
            model_name='user',
            name='philhealth_number',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contributions.philhealthaccount'),
        ),
        migrations.AddField(
            model_name='user',
            name='salary_per_day',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='sss_number',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contributions.sssaccount'),
        ),
    ]
