# Generated by Django 5.0 on 2023-12-20 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0001_initial'),
        ('users', '0004_alter_user_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shift.shift'),
        ),
    ]
