# Generated by Django 5.0 on 2023-12-22 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0001_initial'),
        ('users', '0004_user_number_of_days_user_pag_ibig_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pag_ibig_contribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contributions.pagibig'),
        ),
        migrations.AddField(
            model_name='user',
            name='sss_contribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contributions.sss'),
        ),
    ]
