# Generated by Django 5.0.1 on 2024-01-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_birth_place_alter_user_career_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
