# Generated by Django 5.0 on 2023-12-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_pag_ibig_contribution_user_sss_contribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pag_ibig_number',
            field=models.IntegerField(default=0, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='philhealth_number',
            field=models.IntegerField(default=0, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sss_number',
            field=models.IntegerField(default=0, null=True, unique=True),
        ),
    ]
