# Generated by Django 5.0.1 on 2024-01-31 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_birth_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='suffix',
            field=models.CharField(blank=True, choices=[('', ''), ('Jr.', 'Jr.'), ('Sr.', 'Sr.'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X'), ('Other', 'Other')], default='', max_length=10, null=True),
        ),
    ]
