# Generated by Django 5.0 on 2024-01-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_extras', '0001_initial'),
        ('users', '0006_alter_user_pag_ibig_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deductions',
            field=models.ManyToManyField(to='payroll_extras.deductions'),
        ),
        migrations.AddField(
            model_name='user',
            name='incentives',
            field=models.ManyToManyField(to='payroll_extras.incentives'),
        ),
    ]
