# Generated by Django 5.0 on 2024-01-04 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_remove_kpi_kpi_user'),
        ('users', '0007_user_deductions_user_incentives'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kpi',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms.kpi'),
        ),
    ]
