# Generated by Django 5.0 on 2024-01-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_kpi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pag_ibig_number',
            field=models.IntegerField(default=None, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='philhealth_number',
            field=models.IntegerField(default=None, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='sss_number',
            field=models.IntegerField(default=None, unique=True),
            preserve_default=False,
        ),
    ]
