# Generated by Django 5.0 on 2024-01-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_pag_ibig_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pag_ibig_number',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='philhealth_number',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sss_number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
