# Generated by Django 5.0 on 2024-01-10 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_department_description_position_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['id']},
        ),
    ]
