# Generated by Django 5.0.1 on 2024-02-08 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheetV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_sheets_v2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Time Sheets',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='OTFormV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.TimeField(verbose_name='From')),
                ('to_time', models.TimeField(verbose_name='To')),
                ('reason', models.TextField()),
                ('ts_v2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ot_forms', to='timesheets_v2.timesheetv2')),
            ],
        ),
    ]
