# Generated by Django 5.0 on 2024-01-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_status', models.CharField(choices=[('Probationary', 'Probationary'), ('Contractual', 'Contractual'), ('End of Contract', 'End of Contract'), ('Regular', 'Regular'), ('Resigned', 'Resigned'), ('Retired', 'Retired'), ('Terminated', 'Terminated'), ('Absent without Leave', 'Absent without Leave')], max_length=100)),
                ('career_description', models.TextField()),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Careers',
            },
        ),
    ]
