# Generated by Django 5.0.1 on 2024-03-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careers',
            name='career_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
