# Generated by Django 5.0 on 2023-12-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashadvanceterm',
            name='term',
            field=models.IntegerField(default=0),
        ),
    ]
