# Generated by Django 5.0.1 on 2024-02-08 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overtimeform',
            name='description',
        ),
        migrations.RemoveField(
            model_name='overtimeform',
            name='overtime_hours',
        ),
        migrations.CreateModel(
            name='From_To',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('reason', models.TextField()),
                ('ot_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ot_forms', to='forms.overtimeform')),
            ],
        ),
    ]
