# Generated by Django 5.0 on 2024-01-04 05:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_cashadvanceform_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('metrics', models.TextField()),
                ('min_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('remarks', models.TextField()),
                ('comments', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('kpi_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
