# Generated by Django 5.0 on 2023-12-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_cashadvanceterm_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashadvanceterm',
            name='name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
