# Generated by Django 5.0.1 on 2024-02-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_remove_overtimeform_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequestform',
            name='leave_type',
            field=models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('Vacation Leave', 'Vacation Leave'), ('Maternity Leave', 'Maternity Leave'), ('Paternity Leave', 'Paternity Leave'), ('Half Day Leave', 'Half Day Leave'), ('Undertime', 'Undertime'), ('Other', 'Other')], max_length=50),
        ),
    ]
