# Generated by Django 5.0.1 on 2024-03-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_leaverequestform_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtimeform',
            name='date',
            field=models.DateField(),
        ),
    ]
