# Generated by Django 5.0 on 2024-01-04 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_kpi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpi',
            name='kpi_user',
        ),
    ]
