# Generated by Django 5.0.1 on 2024-02-14 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_alter_leaverequestform_leave_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='from_to',
            old_name='reason',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='temporaryshiftform',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='temporaryshiftform',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='temporaryshiftform',
            name='tempshift_user',
        ),
        migrations.AddField(
            model_name='temporaryshiftform',
            name='temporary_shift_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='temporary_shift_users', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cashadvanceform',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='leaverequestform',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='leaverequestform',
            name='leave_type',
            field=models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('Vacation Leave', 'Vacation Leave'), ('Maternity Leave', 'Maternity Leave'), ('Paternity Leave', 'Paternity Leave'), ('Half Day Leave', 'Half Day Leave'), ('Undertime', 'Undertime'), ('Other', 'Other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='leaverequestform',
            name='leave_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_form', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaverequestform',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='leaverequestform',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Closed', 'Closed')], default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='temporaryshiftform',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='temporaryshiftform',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Closed', 'Closed')], default='Pending', max_length=10)),
                ('adjustment_user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustment_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HalfDayRequestForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('Vacation Leave', 'Vacation Leave'), ('Maternity Leave', 'Maternity Leave'), ('Paternity Leave', 'Paternity Leave'), ('Half Day Leave', 'Half Day Leave'), ('Undertime', 'Undertime'), ('Other', 'Other')], default='Half Day Leave', max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Closed', 'Closed')], default='Pending', max_length=255)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_half_days', to=settings.AUTH_USER_MODEL)),
                ('half_day_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='half_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnderTimeRequestForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('Vacation Leave', 'Vacation Leave'), ('Maternity Leave', 'Maternity Leave'), ('Paternity Leave', 'Paternity Leave'), ('Half Day Leave', 'Half Day Leave'), ('Undertime', 'Undertime'), ('Other', 'Other')], default='Undertime', max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Closed', 'Closed')], default='Pending', max_length=255)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_under_times', to=settings.AUTH_USER_MODEL)),
                ('under_time_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='under_times', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='HalfDayForm',
        ),
    ]
