# Generated by Django 5.0 on 2023-12-20 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_cashadvanceterm_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CashAdvanceTerm',
            new_name='PaymentTerm',
        ),
        migrations.RenameField(
            model_name='cashadvanceform',
            old_name='term',
            new_name='payment_term',
        ),
    ]
