# Generated by Django 5.0.1 on 2024-02-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_rename_reason_from_to_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='from_to',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='from_to',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Closed', 'Closed')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='from_to',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
