# Generated by Django 5.0 on 2024-01-09 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_alter_cashadvanceform_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kpi',
            options={'verbose_name': 'KPI'},
        ),
    ]
