# Generated by Django 5.0 on 2024-01-09 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_alter_kpi_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kpi',
            options={'verbose_name': 'KPI', 'verbose_name_plural': 'KPI'},
        ),
    ]
