# Generated by Django 5.0 on 2024-01-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('label', models.CharField(default='label', max_length=100, null=True)),
                ('is_regular_holiday', models.BooleanField(default=True)),
                ('is_special_non_working_holiday', models.BooleanField(default=False)),
                ('is_special_working_holiday', models.BooleanField(default=False)),
                ('is_company_mandated_unpaid', models.BooleanField(default=False)),
                ('is_company_mandated_paid', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Calendar Events',
                'ordering': ['date'],
            },
        ),
    ]
