<<<<<<< HEAD
# Generated by Django 5.0.1 on 2024-02-06 01:33
=======
# Generated by Django 5.0.1 on 2024-02-06 01:41
>>>>>>> main

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='this_date',
            field=models.DateField(),
        ),
    ]
