# Generated by Django 5.0.1 on 2024-02-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='unformat_date',
            field=models.DateField(),
        ),
    ]
