# Generated by Django 5.0.1 on 2024-02-05 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendarevent',
            old_name='unformat_date',
            new_name='date',
        ),
    ]
