# Generated by Django 5.0 on 2024-01-26 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarevent',
            options={'verbose_name_plural': 'Calendar Events'},
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='date',
        ),
    ]
