# Generated by Django 5.0 on 2024-01-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='label',
            field=models.CharField(default='marc', max_length=100, null=True),
        ),
    ]
