# Generated by Django 5.0.1 on 2024-02-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_rename_unformat_date_calendarevent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='this_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
