# Generated by Django 5.0 on 2024-01-24 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_alter_calendarevent_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='label',
        ),
    ]
