# Generated by Django 5.0 on 2024-01-26 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_alter_calendarevent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='unformat_date',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
