# Generated by Django 5.0.1 on 2024-02-05 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0003_calendarevent_this_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='date',
        ),
    ]
