# Generated by Django 5.0.1 on 2024-02-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0003_calendarevent_unformat_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='description',
            field=models.TextField(default='', null=True),
        ),
    ]
