# Generated by Django 5.0.1 on 2024-02-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0004_remove_calendarevent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='this_date',
            field=models.DateTimeField(),
        ),
    ]
