# Generated by Django 5.0 on 2023-12-22 01:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PagIbig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_share', models.FloatField(default=0.0)),
                ('employee_share', models.FloatField(default=0.0)),
                ('higher_end', models.FloatField(default=5000)),
                ('lower_end', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'PagIbig',
                'verbose_name_plural': 'PagIbig',
            },
        ),
        migrations.CreateModel(
            name='PagIbigAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pag_ibig_number', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhilHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_salary', models.FloatField(default=10000, validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(100000)])),
                ('maximum_salary', models.FloatField(default=100000, validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(100000)])),
                ('rate', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'PhilHealth',
                'verbose_name_plural': 'PhilHealth',
            },
        ),
        migrations.CreateModel(
            name='PhilHealthAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('philhealth_number', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RangeOfCompensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.FloatField(default=9.5)),
                ('employee', models.FloatField(default=4.5)),
            ],
        ),
        migrations.CreateModel(
            name='SSSAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sss_number', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_salary', models.FloatField()),
                ('maximum_salary', models.FloatField()),
                ('employer_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sss_range', to='contributions.rangeofcompensation')),
            ],
            options={
                'verbose_name': 'SSS',
                'verbose_name_plural': 'SSS',
            },
        ),
    ]
