# Generated by Django 5.0 on 2023-12-22 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0001_initial'),
        ('users', '0006_alter_user_pag_ibig_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PagIbigAccount',
        ),
        migrations.DeleteModel(
            name='PhilHealthAccount',
        ),
        migrations.DeleteModel(
            name='SSSAccount',
        ),
    ]
