# Generated by Django 5.0 on 2023-12-22 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0002_delete_pagibigaccount_delete_philhealthaccount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagibig',
            name='year',
            field=models.IntegerField(default=2022),
        ),
    ]
