# Generated by Django 5.0 on 2023-12-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0003_pagibig_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagibig',
            name='year',
            field=models.IntegerField(default=2023, unique=True),
        ),
    ]
