# Generated by Django 5.0 on 2023-12-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0004_alter_pagibig_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='philhealth',
            name='year',
            field=models.IntegerField(default=2023, unique=True),
        ),
    ]
