# Generated by Django 5.0 on 2023-12-22 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0005_philhealth_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='sss',
            name='year',
            field=models.IntegerField(default=2023, unique=True),
        ),
    ]
