# Generated by Django 5.0 on 2023-12-22 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0006_sss_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sss',
            name='year',
        ),
        migrations.AddField(
            model_name='rangeofcompensation',
            name='year',
            field=models.IntegerField(default=2023, unique=True),
        ),
    ]
