# Generated by Django 5.0 on 2024-01-03 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0007_remove_sss_year_rangeofcompensation_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagibig',
            name='year',
            field=models.IntegerField(default=2024, unique=True),
        ),
        migrations.AlterField(
            model_name='philhealth',
            name='year',
            field=models.IntegerField(default=2024, unique=True),
        ),
        migrations.AlterField(
            model_name='rangeofcompensation',
            name='year',
            field=models.IntegerField(default=2024, unique=True),
        ),
    ]
