# Generated by Django 5.0 on 2024-01-03 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0008_alter_pagibig_year_alter_philhealth_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sss',
            old_name='employer_employee',
            new_name='year',
        ),
    ]
