# Generated by Django 5.0 on 2024-01-03 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0009_rename_employer_employee_sss_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagibig',
            old_name='year',
            new_name='pagibig_year',
        ),
        migrations.RenameField(
            model_name='philhealth',
            old_name='year',
            new_name='philhealth_year',
        ),
        migrations.RenameField(
            model_name='rangeofcompensation',
            old_name='year',
            new_name='roc_year',
        ),
        migrations.RenameField(
            model_name='sss',
            old_name='year',
            new_name='sss_year',
        ),
    ]
