# Generated by Django 5.0 on 2024-01-03 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0010_rename_year_pagibig_pagibig_year_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rangeofcompensation',
            options={'verbose_name': 'Range of Compensation', 'verbose_name_plural': 'Range of Compensation'},
        ),
    ]
