# Generated by Django 5.0 on 2024-01-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0011_alter_rangeofcompensation_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagibig',
            old_name='employee_share',
            new_name='employee_share_higher_bracket',
        ),
        migrations.AddField(
            model_name='pagibig',
            name='employee_share_lower_bracket',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='pagibig',
            name='lower_end',
            field=models.FloatField(default=1500),
        ),
    ]
