# Generated by Django 5.0 on 2024-01-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0012_rename_employee_share_pagibig_employee_share_higher_bracket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='philhealth',
            name='philhealth_year',
            field=models.IntegerField(default=2024),
        ),
    ]
