# Generated by Django 5.0 on 2024-01-10 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0013_alter_philhealth_philhealth_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagibig',
            name='pagibig_year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='rangeofcompensation',
            name='roc_year',
            field=models.IntegerField(default=2024),
        ),
    ]
