# Generated by Django 5.0 on 2024-01-12 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('grace_period', models.PositiveIntegerField(blank=True, null=True)),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
                ('monday_on_call', models.BooleanField(default=False)),
                ('tuesday_on_call', models.BooleanField(default=False)),
                ('wednesday_on_call', models.BooleanField(default=False)),
                ('thursday_on_call', models.BooleanField(default=False)),
                ('friday_on_call', models.BooleanField(default=False)),
                ('saturday_on_call', models.BooleanField(default=False)),
                ('sunday_on_call', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_start_time', models.TimeField()),
                ('break_end_time', models.TimeField()),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='shift.shift')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
