# Generated by Django 5.0.1 on 2024-02-05 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['shift_name']},
        ),
    ]
