# Generated by Django 5.0.1 on 2024-02-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0002_leavecounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number_of_Leaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_leaves_in_hours', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Number of Leaves',
                'verbose_name_plural': 'Number of Leaves',
            },
        ),
    ]
