# Generated by Django 5.0.1 on 2024-02-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0003_number_of_leaves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='holiday_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='night_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='overtime_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='regular_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='rest_day',
            field=models.FloatField(),
        ),
    ]
