# Generated by Django 5.0.1 on 2024-01-25 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationFiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_filed', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_vacation', models.SmallIntegerField()),
                ('unused_vacation', models.SmallIntegerField()),
                ('date_of_leave', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('total_vacation', models.SmallIntegerField(default=5)),
                ('vacation_leave', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vacation_filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackers.vacationfiling')),
            ],
            options={
                'verbose_name_plural': 'Leave Tracker',
                'ordering': ['-date_of_leave'],
            },
        ),
    ]
