# Generated by Django 5.0.1 on 2024-01-25 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetracker',
            name='unused_vacation',
        ),
        migrations.RemoveField(
            model_name='leavetracker',
            name='used_vacation',
        ),
    ]
