# Generated by Django 5.0.1 on 2024-01-25 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0002_remove_leavetracker_unused_vacation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetracker',
            name='vacation_filing',
        ),
        migrations.DeleteModel(
            name='VacationFiling',
        ),
    ]
