# Generated by Django 5.0.1 on 2024-01-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0003_remove_leavetracker_vacation_filing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacation_leave', models.IntegerField(default=5)),
            ],
        ),
    ]
