# Generated by Django 5.0.1 on 2024-02-01 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0004_leavecounter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetracker',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavetracker',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
