# Generated by Django 5.0.1 on 2024-02-23 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='cutoff_name',
            field=models.CharField(choices=[('First', 'First'), ('Second', 'Second')], default=None, max_length=255),
            preserve_default=False,
        ),
    ]
