# Generated by Django 5.0.1 on 2024-02-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PayrollRecord',
        ),
        migrations.AddField(
            model_name='payroll',
            name='get_end_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payroll',
            name='get_start_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
