# Generated by Django 5.0.1 on 2024-02-23 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_alter_payroll_cutoff_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='cutoff_name',
        ),
    ]
