# Generated by Django 5.0.1 on 2024-02-23 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_remove_payroll_cutoff_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='cutoff_name',
            field=models.CharField(choices=[('First', 'First'), ('Second', 'Second')], default='First', max_length=255),
        ),
    ]
