# Generated by Django 5.0.1 on 2024-02-23 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_payroll_cutoff_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='cutoff_name',
            field=models.CharField(choices=[('First Cutoff', 'First Cutoff'), ('Second Cutoff', 'Second Cutoff')], default='First Cutoff', max_length=255),
        ),
    ]
