# Generated by Django 5.0.1 on 2024-03-07 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_alter_payroll_cutoff_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='get_end_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='get_start_date',
            new_name='start_date',
        ),
    ]
