# Generated by Django 5.0.1 on 2024-03-07 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_rename_get_end_date_payroll_end_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payroll',
        ),
    ]
