# Generated by Django 5.0.1 on 2024-02-02 03:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_sheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Time Sheets',
                'ordering': ['date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TimeInOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_in_out', to='timesheets.timesheet')),
            ],
            options={
                'verbose_name_plural': 'Time In Out',
                'ordering': ['-date'],
            },
        ),
    ]
