# Generated by Django 5.0.1 on 2024-01-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_upload', models.FileField(upload_to='uploads/')),
                ('employee_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('time_log', models.JSONField()),
            ],
        ),
    ]
