# Generated by Django 5.0.1 on 2024-01-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timelogs',
            options={'verbose_name': 'Time Log', 'verbose_name_plural': 'Time Logs'},
        ),
        migrations.AlterField(
            model_name='timeinout',
            name='time_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeinout',
            name='time_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
