# Generated by Django 5.0.1 on 2024-02-13 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0002_alter_timeinout_options_rename_date_timeinout_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeinout',
            options={'ordering': ['user_date'], 'verbose_name_plural': 'Time In Out'},
        ),
        migrations.RenameField(
            model_name='timeinout',
            old_name='user',
            new_name='user_date',
        ),
    ]
