# Generated by Django 5.0.1 on 2024-01-23 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0002_alter_timelogs_options_alter_timeinout_time_in_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timesheet',
            options={'ordering': ['date'], 'verbose_name_plural': 'Time Sheets'},
        ),
    ]
