# Generated by Django 5.0.1 on 2024-01-31 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0002_timeinout_schedule_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeinout',
            name='adjusted_time_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
