# Generated by Django 5.0.1 on 2024-01-31 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0003_timeinout_adjusted_time_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeinout',
            name='adjusted_time_out',
        ),
    ]
