# Generated by Django 5.0.1 on 2024-01-31 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0004_remove_timeinout_adjusted_time_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeinout',
            name='schedule_category',
        ),
    ]
