# Generated by Django 5.0.1 on 2024-02-13 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0004_alter_timeinout_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeinout',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Time In Out'},
        ),
        migrations.RenameField(
            model_name='timeinout',
            old_name='user',
            new_name='date',
        ),
    ]
