# Generated by Django 5.0.1 on 2024-02-16 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0005_alter_timeinout_options_rename_user_timeinout_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeinout',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Time In/Out'},
        ),
        migrations.AlterModelOptions(
            name='timesheet',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Time Sheets'},
        ),
        migrations.AddField(
            model_name='timesheet',
            name='time_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='time_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_sheets_v2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OTFormV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.TimeField(verbose_name='From')),
                ('to_time', models.TimeField(verbose_name='To')),
                ('reason', models.TextField()),
                ('ts_v2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ot_forms', to='timesheets.timesheet')),
            ],
        ),
    ]
