# Generated by Django 5.0.1 on 2024-01-31 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0005_remove_timeinout_schedule_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeinout',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
