# Generated by Django 5.0.1 on 2024-02-22 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0006_alter_timeinout_options_alter_timesheet_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeinout',
            options={'ordering': ['-timesheet'], 'verbose_name_plural': 'Time In/Out'},
        ),
        migrations.RenameField(
            model_name='timeinout',
            old_name='date',
            new_name='timesheet',
        ),
    ]
