# Generated by Django 5.0.1 on 2024-01-31 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0007_remove_timeinout_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeinout',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
