# Generated by Django 5.0.1 on 2024-01-31 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0008_timeinout_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeinout',
            name='status',
        ),
    ]
