# Generated by Django 5.0.1 on 2024-02-22 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0008_alter_timeinout_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='time_in',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='time_out',
        ),
    ]
