# Generated by Django 5.0.1 on 2024-03-04 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0009_remove_timesheet_time_in_remove_timesheet_time_out'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeinout',
            options={'ordering': ['-user_date'], 'verbose_name_plural': 'Time In/Out'},
        ),
        migrations.RenameField(
            model_name='timeinout',
            old_name='date',
            new_name='user_date',
        ),
    ]
