# Generated by Django 5.0.1 on 2024-01-31 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0009_remove_timeinout_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeinout',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
