# Generated by Django 5.0.1 on 2024-02-23 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0009_remove_timesheet_time_in_remove_timesheet_time_out'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timesheet',
            options={'ordering': ['user_id'], 'verbose_name_plural': 'Time Sheets'},
        ),
    ]
