# Generated by Django 5.0.1 on 2024-03-04 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0010_alter_timeinout_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeinout',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Time In/Out'},
        ),
        migrations.RenameField(
            model_name='timeinout',
            old_name='user_date',
            new_name='date',
        ),
    ]
