# Generated by Django 5.0.1 on 2024-01-31 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0010_timeinout_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeinout',
            name='category',
        ),
    ]
