# Generated by Django 5.0.1 on 2024-01-31 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0011_remove_timeinout_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeinout',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
