# Generated by Django 5.0.1 on 2024-03-07 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0010_alter_timesheet_options'),
        ('timesheets', '0011_alter_timeinout_options_and_more'),
    ]

    operations = [
    ]
