# Generated by Django 5.0.1 on 2024-03-07 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0012_merge_20240307_0901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timesheet',
            options={'ordering': ['date'], 'verbose_name_plural': 'Time Sheets'},
        ),
    ]
