# Generated by Django 5.0.1 on 2024-02-01 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0013_alter_timesheet_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeinout',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
