# Generated by Django 5.0 on 2024-01-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deductions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_name', models.CharField(max_length=50, unique=True)),
                ('deduction_amount', models.FloatField(default=0.0)),
                ('include_in_users', models.BooleanField(default=False)),
                ('deduction_status', models.BooleanField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incentives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incentive_name', models.CharField(max_length=50, unique=True)),
                ('incentive_amount', models.FloatField(default=0.0)),
                ('include_in_users', models.BooleanField(default=False)),
                ('incentive_status', models.BooleanField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
