# Generated by Django 5.0 on 2024-01-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_extras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deductions',
            name='deduction_status',
            field=models.BooleanField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')]),
        ),
        migrations.AlterField(
            model_name='incentives',
            name='incentive_status',
            field=models.BooleanField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')]),
        ),
    ]
