# Generated by Django 5.0 on 2024-01-03 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_extras', '0002_alter_deductions_deduction_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deductions',
            options={'verbose_name': 'Deduction', 'verbose_name_plural': 'Deductions'},
        ),
        migrations.AlterModelOptions(
            name='incentives',
            options={'verbose_name': 'Incentive', 'verbose_name_plural': 'Incentives'},
        ),
    ]
