# Generated by Django 5.0 on 2024-01-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_extras', '0003_alter_deductions_options_alter_incentives_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incentives',
            name='incentive_status',
            field=models.BooleanField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10),
        ),
    ]
