# Generated by Django 5.0 on 2024-01-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_extras', '0004_alter_incentives_incentive_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incentives',
            name='incentive_status',
            field=models.BooleanField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=15),
        ),
    ]
