# Generated by Django 5.0 on 2024-01-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_extras', '0005_alter_incentives_incentive_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deductions',
            name='deduction_status',
            field=models.BooleanField(choices=[('Active', 'ON'), ('Inactive', 'OFF')]),
        ),
        migrations.AlterField(
            model_name='incentives',
            name='incentive_status',
            field=models.BooleanField(choices=[('Active', 'ON'), ('Inactive', 'OFF')], max_length=15),
        ),
    ]
