# Generated by Django 5.0 on 2024-01-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_extras', '0007_alter_deductions_deduction_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deductions',
            name='deduction_status',
            field=models.CharField(choices=[('Active_On', 'ON'), ('Inactive_Off', 'OFF')], max_length=50),
        ),
        migrations.AlterField(
            model_name='incentives',
            name='incentive_status',
            field=models.CharField(choices=[('Active_On', 'ON'), ('Inactive_Off', 'OFF')], max_length=50),
        ),
    ]
