# Generated by Django 5.0 on 2024-01-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_extras', '0008_alter_deductions_deduction_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deductions',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='incentives',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
