# Generated by Django 5.0 on 2024-01-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_extras', '0009_alter_deductions_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deductions',
            name='deduction_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=50),
        ),
        migrations.AlterField(
            model_name='incentives',
            name='incentive_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=50),
        ),
    ]
