# Generated by Django 5.0 on 2024-01-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_extras', '0011_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='rating_amount',
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='rating_name',
        ),
        migrations.AddField(
            model_name='ratings',
            name='holiday_rate',
            field=models.FloatField(default=2.0),
        ),
        migrations.AddField(
            model_name='ratings',
            name='night_rate',
            field=models.FloatField(default=1.1),
        ),
        migrations.AddField(
            model_name='ratings',
            name='overtime_rate',
            field=models.FloatField(default=1.25),
        ),
        migrations.AddField(
            model_name='ratings',
            name='regular_rate',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='ratings',
            name='rest_day',
            field=models.FloatField(default=1.3),
        ),
        migrations.AddField(
            model_name='ratings',
            name='year',
            field=models.IntegerField(default=2024),
        ),
    ]
