# Generated by Django 5.0 on 2024-01-10 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_extras', '0012_remove_ratings_rating_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='include_in_users',
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='rating_status',
        ),
    ]
