# Generated by Django 5.0 on 2024-01-17 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_timeout_date_timeinput_delete_timein_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeinput',
            options={'ordering': ['time_input']},
        ),
    ]
